Javascript-Capstone
vanelnw/JavaScript-Capstone pull request #7
Opened 2022-11-25 16:07 UTC by vanelnw

In this project, we :

- create an E-commerce application an implement likes and comment functionality .
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use callbacks and promises.
- Use webpack to bundle JavaScript.\
- Use npm as a package manager.
- Use API documentation.
- Send and receive data from an API.
- Write unit tests for a JavaScript app.
- Use the AAA pattern for unit tests.

2022-11-25 17:08 UTC, rloterh requested changes
Hi Vanel & Raymond, 

You did extremely great on this project! 👏 👏
There are some issues that you still need to work on to prepare your project for the assessment but you are almost there 🚦 🚦

## Suggested changes
_Kindly check my inline comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._ 😃 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-25 17:08 UTC, rloterh commented on src/style.css
> +.commentSection > * {
- [ ] OPTIONAL
Your comment overlay appears to be very opaque. Overlays generally have some form transparent background, and likewise, I think you apply some amount of transparent effect to the background of your comment overlay. 

**Your comment overlay:**
![image](https://user-images.githubusercontent.com/12745474/204025580-8cd5d624-49d0-4d64-b3e8-26888e64df3f.png)

2022-11-25 17:08 UTC, rloterh commented on src/modules/commentsCounter.js
> +const countElement = () => {
- [ ] Your comment counter is not working as desired. When a comment is added the counter is not updated immediately, until the page is refreshed. Kindly ensure that the comment counter updates the same time as the comment entered by a user is persisted.
- [ ] Also, as per the design guidelines, comments should appear above the form.

**Comments counter delay:**
![image](https://user-images.githubusercontent.com/12745474/204026807-6b465d12-46f3-494d-80e1-1970cf654ba8.png)

2022-11-25 17:08 UTC, rloterh commented on src/index.js
> +  const Likes = await fetch(
- [ ]  OPTIONAL
I think you can improve upon your _likes_ features to make it appear more realistic in these ways:
    - Like icon should toggle to indicate _like_ or _unlike_ when a particular user clicks on the like icon. If the page is refreshed, then assume that new user is present.
    - Total count of likes per user/site visitor should be 1. So, let's assume a user clicks a like, and the number of likes for a particular item should be `+1`, and if the same user clicks the like again the number of likes for that same object should be `-1`. If the page is refreshed, then assume that new user is present. 😉

2022-11-25 17:08 UTC, rloterh commented on README.md
> +- [Live Demo Link](https://vanelnw.github.io/JavaScript-Capstone/)
- [ ] OPTIONAL
Live demo is pointing to the ReadMe. Kindly ensure to update your demo link accordingly.

2022-11-25 17:08 UTC, rloterh commented on README.md
> +
- [ ] OPTIONAL
 Kindly ensure to add the _Future Features_ to your ReadMe, which should include 1-3 potential features to be added

2022-11-26 11:45 UTC, OyePriscilla approved these changes
Hi @vanelnw  and @dialite 😃, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![GloriousTenderHalcyon-max-1mb](https://user-images.githubusercontent.com/103386183/196425494-5b87178d-78f7-4044-a7d2-3461b0a96ef8.gif)

## Highlights
Descriptive pull request message and title :heavy_check_mark: 
Linter error checks validated :heavy_check_mark: 
Commit messages are meaningful. :heavy_check_mark: 
GitHub flow observed ✔️

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-11-26 11:45 UTC, OyePriscilla commented on README.md
> +- [Live Demo Link](https://vanelnw.github.io/JavaScript-Capstone/)
- [ ] [optional] Kindly update your` live demo` to display your app properly. Perhaps you may want to build your app with `gh-pages.` You can read through [this short tutorial](https://github.com/turingschool-examples/webpack-starter-kit/blob/main/gh-pages-procedure.md).

2022-11-26 12:08 UTC, merged

2022-12-11 14:58 UTC, dialite commented
###Hi @vanelnw 

In my opinion, the  project approval is a well deserved one. Congratulations.! 🎉🎉 🎉

##Suggestion

Please in reaction to the optional change that was suggested by the reviewer, I will suggest if we can add the '/dist' to the end of the link so that GitHub page deploy can locate the 'index.html' file which is required. 

Thank you.
Once again Congratulations! 🎉 🎉 🎉 🎉 🎉 🎉 🎉